- name: Add ELRepo
  yum:
    name: https://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
    state: installed
- name: Install latest mainline kernel
  yum:
    name: kernel-ml
    state: installed
    enablerepo: elrepo-kernel
- name: Remake grub config to pick up new kernel
  command: grub2-set-default 1
- name: Restart server to ensure configuration changes take hold
  shell: 'sleep 2 && shutdown -r now "Reboot triggered by Ansible" && sleep 5'
  async: 1
  poll: 0
  become: true
- name: Wait for server to restart
  reboot:
    reboot_timeout: 3600
   
- name: enable bbr module in boot
  blockinfile:
    dest: /etc/modules-load.d/modules.conf
    block: |
      tcp_bbr
- name: add the tcp_bbr module
  modprobe:
    name: tcp_bbr
    state: present

- name: ensure bbr is enabled
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {name: "net.core.default_qdisc", value: "fq"}
    - {name: "net.ipv4.tcp_congestion_control", value: "bbr"}
