# Playbook to deploy prometheus&grafana

- name: Copy grafana.repo
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    
- name: Install grafana
  yum:
    name: grafana-enterprise
    state: present

- name: Change the grafana admin password
  command: grafana-cli admin reset-admin-password 123
  
  
- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started
 
