# Playbook to deploy prometheus&grafana

- name: Copy grafana.repo
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    
- name: Install grafana
  yum:
    name: grafana-enterprise
    state: installed

- name: Change the grafana admin password
  command: grafana-cli admin reset-admin-password testparolası
  
- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started
    
- name: create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false
    home: "{{ prometheus_dir }}"


 
